### PR TITLE
Add keras_ssd7 to requirements

### PR DESCRIPTION
**Pull request by kegl**

### CODE REVIEW

**Comment by kegl** [comment]
@jorisvandenbossche @aboucaud predict output should be an np.array of objects otherwise cv bagging crashes. We should enforce it in the `__init__` of the detection prediction type.

Also: please don't output the weights in every epoch.

**Comment by jorisvandenbossche** [comment]
Can you remove the changes to the notebook? 
There is actually also an error traceback in the notebook from running `ramp_test_submission`, is that an error we should look into?

> Also: please don't output the weights in every epoch.

It only saves the best, not in every epoch. And in https://github.com/ramp-kits/mars_craters/pull/49 I also changed it to use a fixed name (thus overwriting previous best ones, so there is only one file with weights written in the end)

**Comment by kegl** [comment]
Please do the changes, I won't have time today. And merge these two PRs into one if possible.

**Comment by kegl** [comment]
The most important thing would be to check that the predict output complies with "np.array of objects (list)" requirement, in the ramp-workflow detector prediction type.

**Comment by jorisvandenbossche** [comment]
Limited this here to only the requirements, continue on predict output in https://github.com/ramp-kits/mars_craters/pull/55

**Pull request merged**
