### PR TITLE
FIX remove bug when cropping patch

### PR DESCRIPTION
**Pull request by glemaitre**
Upsss

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
This can be merged?

**Comment by glemaitre** [comment]
‎I need to push the version using the scale.

**Comment by jorisvandenbossche** [comment]
But in the diff you are already using `scale_surf = radius / self.min_radius` ?

**Comment by glemaitre** [comment]
Oh yes I misread the diff. But x and y need to be exchanged

**Comment by glemaitre** [comment]
So it should be fine now.

**Pull request merged**
